<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('shop_categories', function (Blueprint $table) {
            $table->id(); $table->string('name')->unique(); $table->text('description')->nullable(); $table->boolean('supports_repair')->default(false); $table->string('status')->default('Active'); $table->timestamps();
        });

        Schema::create('shops', function (Blueprint $table) {
            $table->id(); $table->foreignId('shop_category_id')->nullable()->constrained('shop_categories')->nullOnDelete(); $table->unsignedBigInteger('owner_id')->nullable();
            $table->string('name'); $table->text('address')->nullable(); $table->string('contact_number')->nullable(); $table->string('gst_number')->nullable(); $table->string('logo')->nullable();
            $table->decimal('opening_balance',12,2)->default(0); $table->string('currency',10)->default('INR'); $table->string('invoice_prefix',20)->default('INV'); $table->decimal('default_tax',8,2)->default(0); $table->decimal('low_stock_alert',12,2)->default(5);
            $table->string('status')->default('Active'); $table->json('settings')->nullable(); $table->timestamps();
        });

        Schema::table('users', function (Blueprint $table) {
            if (!Schema::hasColumn('users', 'shop_id')) $table->foreignId('shop_id')->nullable()->after('id')->constrained('shops')->nullOnDelete();
            if (!Schema::hasColumn('users', 'mobile')) $table->string('mobile')->nullable()->after('email');
            if (!Schema::hasColumn('users', 'role')) $table->string('role')->default('shop_owner')->after('password');
            if (!Schema::hasColumn('users', 'status')) $table->string('status')->default('Active')->after('role');
            if (!Schema::hasColumn('users', 'permissions')) $table->json('permissions')->nullable()->after('status');
        });

        Schema::create('product_categories', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->text('description')->nullable(); $table->string('status')->default('Active'); $table->timestamps(); });
        Schema::create('suppliers', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->string('mobile')->nullable(); $table->text('address')->nullable(); $table->string('product_supplied')->nullable(); $table->decimal('total_purchase',12,2)->default(0); $table->decimal('paid_amount',12,2)->default(0); $table->decimal('due_amount',12,2)->default(0); $table->string('status')->default('Active'); $table->timestamps(); });
        Schema::create('products', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('product_category_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('supplier_id')->nullable()->constrained()->nullOnDelete(); $table->string('name'); $table->string('sku')->nullable(); $table->string('barcode')->nullable(); $table->string('image')->nullable(); $table->decimal('purchase_price',12,2)->default(0); $table->decimal('selling_price',12,2)->default(0); $table->decimal('quantity',12,2)->default(0); $table->string('unit_type')->default('pcs'); $table->decimal('opening_stock',12,2)->default(0); $table->decimal('low_stock_alert',12,2)->default(5); $table->string('status')->default('Active'); $table->timestamps(); });
        Schema::create('stock_histories', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('product_id')->constrained()->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->string('type'); $table->decimal('quantity',12,2); $table->decimal('before_quantity',12,2); $table->decimal('after_quantity',12,2); $table->text('note')->nullable(); $table->string('reference_type')->nullable(); $table->unsignedBigInteger('reference_id')->nullable(); $table->timestamps(); });
        Schema::create('customers', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->string('name'); $table->string('mobile')->nullable(); $table->text('address')->nullable(); $table->string('photo')->nullable(); $table->text('notes')->nullable(); $table->decimal('total_purchase',12,2)->default(0); $table->decimal('total_paid',12,2)->default(0); $table->decimal('total_due',12,2)->default(0); $table->date('last_payment_date')->nullable(); $table->string('status')->default('Active'); $table->timestamps(); });
        Schema::create('sales', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->string('invoice_no')->unique(); $table->decimal('subtotal',12,2)->default(0); $table->decimal('discount',12,2)->default(0); $table->decimal('tax',12,2)->default(0); $table->decimal('total_amount',12,2)->default(0); $table->decimal('paid_amount',12,2)->default(0); $table->decimal('due_amount',12,2)->default(0); $table->string('payment_method')->nullable(); $table->string('payment_status')->default('Due'); $table->string('sale_status')->default('Completed'); $table->timestamp('sale_date')->nullable(); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('sale_items', function (Blueprint $table) { $table->id(); $table->foreignId('sale_id')->constrained()->cascadeOnDelete(); $table->foreignId('product_id')->nullable()->constrained()->nullOnDelete(); $table->string('product_name'); $table->decimal('quantity',12,2); $table->decimal('purchase_price',12,2); $table->decimal('selling_price',12,2); $table->decimal('discount',12,2)->default(0); $table->decimal('total',12,2); $table->decimal('profit',12,2)->default(0); $table->timestamps(); });
        Schema::create('payments', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->nullableMorphs('payable'); $table->string('payment_no')->unique(); $table->decimal('amount',12,2); $table->string('method')->default('cash'); $table->string('type')->default('sale_payment'); $table->text('note')->nullable(); $table->timestamp('paid_at')->nullable(); $table->timestamps(); });
        Schema::create('due_payments', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('sale_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('repair_id')->nullable(); $table->decimal('amount',12,2); $table->decimal('paid_amount',12,2)->default(0); $table->decimal('remaining_amount',12,2)->default(0); $table->date('reminder_date')->nullable(); $table->string('status')->default('Due'); $table->text('note')->nullable(); $table->timestamps(); });
        Schema::create('repairs', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('customer_id')->nullable()->constrained()->nullOnDelete(); $table->foreignId('assigned_user_id')->nullable()->constrained('users')->nullOnDelete(); $table->string('repair_no')->unique(); $table->string('item_name'); $table->string('brand_model')->nullable(); $table->text('problem_description'); $table->text('item_condition')->nullable(); $table->date('received_date')->nullable(); $table->date('expected_return_date')->nullable(); $table->decimal('estimated_amount',12,2)->default(0); $table->decimal('advance_amount',12,2)->default(0); $table->decimal('remaining_amount',12,2)->default(0); $table->text('parts_used')->nullable(); $table->decimal('service_charge',12,2)->default(0); $table->string('status')->default('Received'); $table->string('delivery_status')->default('Pending'); $table->text('notes')->nullable(); $table->timestamps(); });
        Schema::create('expenses', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $table->string('category'); $table->string('title'); $table->decimal('amount',12,2); $table->date('expense_date'); $table->string('payment_method')->nullable(); $table->text('note')->nullable(); $table->timestamps(); });
        Schema::create('notifications', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->nullable()->constrained()->cascadeOnDelete(); $table->foreignId('user_id')->nullable()->constrained()->cascadeOnDelete(); $table->string('title'); $table->text('message'); $table->string('type')->default('info'); $table->timestamp('read_at')->nullable(); $table->json('data')->nullable(); $table->timestamps(); });
        Schema::create('subscription_plans', function (Blueprint $table) { $table->id(); $table->string('name'); $table->decimal('price',12,2)->default(0); $table->integer('duration_days')->default(30); $table->integer('max_staff')->default(1); $table->integer('max_products')->default(100); $table->json('features')->nullable(); $table->string('status')->default('Active'); $table->timestamps(); });
        Schema::create('shop_subscriptions', function (Blueprint $table) { $table->id(); $table->foreignId('shop_id')->constrained()->cascadeOnDelete(); $table->foreignId('subscription_plan_id')->nullable()->constrained()->nullOnDelete(); $table->date('start_date'); $table->date('end_date'); $table->decimal('amount',12,2)->default(0); $table->string('payment_status')->default('Pending'); $table->string('status')->default('Active'); $table->timestamps(); });
    }

    public function down(): void
    {
        Schema::dropIfExists('shop_subscriptions'); Schema::dropIfExists('subscription_plans'); Schema::dropIfExists('notifications'); Schema::dropIfExists('expenses'); Schema::dropIfExists('repairs'); Schema::dropIfExists('due_payments'); Schema::dropIfExists('payments'); Schema::dropIfExists('sale_items'); Schema::dropIfExists('sales'); Schema::dropIfExists('customers'); Schema::dropIfExists('stock_histories'); Schema::dropIfExists('products'); Schema::dropIfExists('suppliers'); Schema::dropIfExists('product_categories'); Schema::dropIfExists('shops'); Schema::dropIfExists('shop_categories');
    }
};
